// Animation names
#define WOMAN_ANIM_DEFAULT_ANIMATION 0
#define WOMAN_ANIM_AIRATTACK01 1
#define WOMAN_ANIM_AIRATTACK02 2
#define WOMAN_ANIM_AIRDEATH 3
#define WOMAN_ANIM_AIRFLY 4
#define WOMAN_ANIM_AIRSTAND 5
#define WOMAN_ANIM_AIRWOUND01 6
#define WOMAN_ANIM_AIRWOUND02 7
#define WOMAN_ANIM_GROUNDATTACK01 8
#define WOMAN_ANIM_GROUNDATTACK02 9
#define WOMAN_ANIM_GROUNDDEATH01 10
#define WOMAN_ANIM_GROUNDDEATH02 11
#define WOMAN_ANIM_GROUNDRUN 12
#define WOMAN_ANIM_GROUNDSTAND 13
#define WOMAN_ANIM_GROUNDTOAIR 14
#define WOMAN_ANIM_AIRTOGROUND 15
#define WOMAN_ANIM_GROUNDWALK 16
#define WOMAN_ANIM_GROUNDWOUND03 17
#define WOMAN_ANIM_GROUNDWOUND04 18
#define WOMAN_ANIM_GROUNDWOUND05 19

// Color names

// Patch names

// Names of collision boxes
#define WOMAN_COLLISION_BOX_GROUND 0
#define WOMAN_COLLISION_BOX_AIR 1
#define WOMAN_COLLISION_BOX_DEATH  2

// Attaching position names

// Sound names
