// Animation names
#define GRENADELAUNCHERITEM_ANIM_DEFAULT_ANIMATION 0

// Color names

// Patch names

// Names of collision boxes
#define GRENADELAUNCHERITEM_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define GRENADELAUNCHERITEM_ATTACHMENT_SECOND_PART 0
#define GRENADELAUNCHERITEM_ATTACHMENT_MAIN_PART 1
#define GRENADELAUNCHERITEM_ATTACHMENT_THRID_PART 2
#define GRENADELAUNCHERITEM_ATTACHMENT_LAST_PART 3

// Sound names
