// Animation names
#define BODY_ANIM_FORMIPMODELS 0
//#define BODY_ANIM_DEFAULT_ANIMATION BODY_ANIM_FORMIPMODELS
//######################################
#define BODY_ANIM_KNIFE_CROUCHWALK 1
#define BODY_ANIM_KNIFE_CROUCHSTAND 2
#define BODY_ANIM_KNIFE_JUMP_START 3
#define BODY_ANIM_KNIFE_JUMP_END 4
#define BODY_ANIM_KNIFE_PUSH 5
#define BODY_ANIM_KNIFE_PULL 6
#define BODY_ANIM_KNIFE_PUSHPULL 7
//
#define BODY_ANIM_KNIFE_SWIMMING 8
#define BODY_ANIM_KNIFE_SWIM_ATTACK BODY_ANIM_KNIFE_SWIMMING
//#define BODY_ANIM_KNIFE_SWIM_ATTACK 12
//
#define BODY_ANIM_KNIFE_TURNING 9
#define BODY_ANIM_KNIFE_STAND 10
#define BODY_ANIM_KNIFE_WALKRUN 11
//
#define BODY_ANIM_KNIFE_ATTACK 12
//#define BODY_ANIM_KNIFE_ATTACK 6
//######################################
#define BODY_ANIM_MINIGUN_CROUCHWALK 13
#define BODY_ANIM_MINIGUN_REDRAWSLOW BODY_ANIM_MINIGUN_CROUCHWALK
#define BODY_ANIM_MINIGUN_CROUCHSTAND 14
//
#define BODY_ANIM_MINIGUN_JUMP_START 15
#define BODY_ANIM_MINIGUN_DRAW BODY_ANIM_MINIGUN_JUMP_START
#define BODY_ANIM_MINIGUN_JUMP_END 16
#define BODY_ANIM_MINIGUN_REDRAW BODY_ANIM_MINIGUN_JUMP_END
#define BODY_ANIM_MINIGUN_PUSH 17
#define BODY_ANIM_MINIGUN_SWIM_REDRAW BODY_ANIM_MINIGUN_PUSH
#define BODY_ANIM_MINIGUN_PULL 18
#define BODY_ANIM_MINIGUN_SWIM_DRAW BODY_ANIM_MINIGUN_PULL
#define BODY_ANIM_MINIGUN_PUSHPULL 19
#define BODY_ANIM_MINIGUN_SWIM_FIRESHORT BODY_ANIM_MINIGUN_PUSHPULL
#define BODY_ANIM_MINIGUN_SWIMMING 20
#define BODY_ANIM_MINIGUN_SWIM_FIRELONG BODY_ANIM_MINIGUN_SWIMMING
#define BODY_ANIM_MINIGUN_TURNING 21
#define BODY_ANIM_MINIGUN_FIRELONG BODY_ANIM_MINIGUN_TURNING
#define BODY_ANIM_MINIGUN_WALKRUN 22
#define BODY_ANIM_MINIGUN_FIRESHORT BODY_ANIM_MINIGUN_WALKRUN
#define BODY_ANIM_MINIGUN_STAND 23
//######################################
#define BODY_ANIM_COLT_CROUCHWALK 24
#define BODY_ANIM_COLT_CROUCHSTAND 25
#define BODY_ANIM_COLT_JUMP_START 26
#define BODY_ANIM_COLT_DRAW BODY_ANIM_COLT_JUMP_START
#define BODY_ANIM_COLT_JUMP_END 27
#define BODY_ANIM_COLT_REDRAW BODY_ANIM_COLT_JUMP_END
#define BODY_ANIM_COLT_PUSH 28
#define BODY_ANIM_COLT_SWIM_REDRAW BODY_ANIM_COLT_PUSH
#define BODY_ANIM_COLT_PULL 29
#define BODY_ANIM_COLT_SWIM_DRAW BODY_ANIM_COLT_PULL
//
#define BODY_ANIM_PUSHTOWALKCOLT 54
#define BODY_ANIM_COLT_REDRAWSLOW BODY_ANIM_PUSHTOWALKCOLT
//#define BODY_ANIM_COLT_PUSHPULL 30
#define BODY_ANIM_COLT_PUSHPULL BODY_ANIM_COLT_REDRAWSLOW
#define BODY_ANIM_COLT_SWIMMING 31
#define BODY_ANIM_COLT_SWIM_STAND BODY_ANIM_COLT_SWIMMING
#define BODY_ANIM_COLT_TURNING 32
#define BODY_ANIM_COLT_FIRERIGHT BODY_ANIM_COLT_TURNING
#define BODY_ANIM_COLT_WALKRUN 33
#define BODY_ANIM_COLT_FIRELEFT BODY_ANIM_COLT_WALKRUN
#define BODY_ANIM_COLT_STAND 34
//######################################
#define BODY_ANIM_SHOTGUN_CROUCHWALK 35
#define BODY_ANIM_SHOTGUN_CROUCHSTAND 36
#define BODY_ANIM_SHOTGUN_JUMP_START 37
#define BODY_ANIM_SHOTGUN_DRAW BODY_ANIM_SHOTGUN_JUMP_START
#define BODY_ANIM_SHOTGUN_JUMP_END 38
#define BODY_ANIM_SHOTGUN_REDRAW BODY_ANIM_SHOTGUN_JUMP_END
#define BODY_ANIM_SHOTGUN_PUSH 39
#define BODY_ANIM_SHOTGUN_SWIM_REDRAW BODY_ANIM_SHOTGUN_PUSH
#define BODY_ANIM_SHOTGUN_PULL 40
#define BODY_ANIM_SHOTGUN_SWIM_DRAW BODY_ANIM_SHOTGUN_PULL
#define BODY_ANIM_SHOTGUN_PUSHPULL 41
#define BODY_ANIM_SHOTGUN_REDRAWSLOW BODY_ANIM_SHOTGUN_PUSHPULL
#define BODY_ANIM_SHOTGUN_SWIMMING 42
#define BODY_ANIM_SHOTGUN_SWIM_STAND BODY_ANIM_SHOTGUN_SWIMMING
#define BODY_ANIM_SHOTGUN_TURNING 43
#define BODY_ANIM_SHOTGUN_FIRELONG BODY_ANIM_SHOTGUN_TURNING
#define BODY_ANIM_SHOTGUN_WALKRUN 44
#define BODY_ANIM_SHOTGUN_FIRESHORT BODY_ANIM_SHOTGUN_WALKRUN
#define BODY_ANIM_SHOTGUN_STAND 45
//######################################
#define BODY_ANIM_BODY_DEATH_NORMAL 46
#define BODY_ANIM_DEATH_FORWARD BODY_ANIM_BODY_DEATH_NORMAL
#define BODY_ANIM_BODY_DEATH_UNDERWATER 47
#define BODY_ANIM_DEATH_UNDERWATER BODY_ANIM_BODY_DEATH_UNDERWATER
#define BODY_ANIM_BODY_DEATH_SPIKES 48
#define BODY_ANIM_DEATH_SPIKES BODY_ANIM_BODY_DEATH_SPIKES
//######################################
#define BODY_ANIM_STATUE_PULL 49 //
//######################################
#define BODY_ANIM_LOOKAROUNDONCE 50 //
#define BODY_ANIM_NORMALWALK 51 //
#define BODY_ANIM_WAIT 53 //
//#define BODY_ANIM_PUSHTOWALK 52
#define BODY_ANIM_PUSHTOWALK BODY_ANIM_WAIT
//
//////#define BODY_ANIM_PUSHTOWALKCOLT 54
//////#define BODY_ANIM_COLT_REDRAWSLOW BODY_ANIM_PUSHTOWALKCOLT
//#define BODY_ANIM_PUSHTOWALKKNIFE 55
#define BODY_ANIM_PUSHTOWALKKNIFE BODY_ANIM_WAIT
//
#define BODY_ANIM_WAITTOLOOKAROUND 56 //
#define BODY_ANIM_LOOKAROUNDTOWAIT 57 //
//#define BODY_ANIM_KNIFE_PUSH_SLOW 58
#define BODY_ANIM_KNIFE_PUSH_SLOW BODY_ANIM_WAIT
//
#define BODY_ANIM_MINIGUN_PUSH_SLOW 59
#define BODY_ANIM_MINIGUN_DEACTIVATETOWALK BODY_ANIM_MINIGUN_PUSH_SLOW
#define BODY_ANIM_COLT_PUSH_SLOW 60
#define BODY_ANIM_COLT_DEACTIVATETOWALK BODY_ANIM_COLT_PUSH_SLOW
#define BODY_ANIM_SHOTGUN_PUSH_SLOW 61
#define BODY_ANIM_SHOTGUN_DEACTIVATETOWALK BODY_ANIM_SHOTGUN_PUSH_SLOW
#define BODY_ANIM_LOOKAROUND 62
//
//
//#######################################################################
//#######################################################################
// Animation names
//#define BODY_ANIM_DEFAULT_ANIMATION 0
//#define BODY_ANIM_COLT_STAND 1
//#define BODY_ANIM_COLT_REDRAW 2
//#define BODY_ANIM_COLT_DRAW 3
//#define BODY_ANIM_COLT_FIRERIGHT 4
//#define BODY_ANIM_COLT_FIRELEFT 5
//#define BODY_ANIM_KNIFE_ATTACK 6
//#define BODY_ANIM_COLT_SWIM_STAND 7
//#define BODY_ANIM_COLT_SWIM_REDRAW 8
//#define BODY_ANIM_COLT_SWIM_DRAW 9
//#define BODY_ANIM_COLT_SWIM_FIRERIGHT 10
//#define BODY_ANIM_COLT_SWIM_FIRELEFT 11

//#define BODY_ANIM_KNIFE_SWIM_ATTACK 12
//#define BODY_ANIM_SHOTGUN_STAND 13
//#define BODY_ANIM_SHOTGUN_REDRAW 14
//#define BODY_ANIM_SHOTGUN_DRAW 15
//#define BODY_ANIM_SHOTGUN_FIRELONG 16
//#define BODY_ANIM_SHOTGUN_FIRESHORT 17
//#define BODY_ANIM_SHOTGUN_SWIM_STAND 18
//#define BODY_ANIM_SHOTGUN_SWIM_REDRAW 19
//#define BODY_ANIM_SHOTGUN_SWIM_DRAW 20
//#define BODY_ANIM_SHOTGUN_SWIM_FIRELONG 21
//#define BODY_ANIM_SHOTGUN_SWIM_FIRESHORT 22

//#define BODY_ANIM_MINIGUN_STAND 23
//#define BODY_ANIM_MINIGUN_REDRAW 24
//#define BODY_ANIM_MINIGUN_DRAW 25
//#define BODY_ANIM_MINIGUN_FIRELONG 26
//#define BODY_ANIM_MINIGUN_FIRESHORT 27
//#define BODY_ANIM_MINIGUN_SWIM_STAND 28
//#define BODY_ANIM_MINIGUN_SWIM_REDRAW 29
//#define BODY_ANIM_MINIGUN_SWIM_DRAW 30
//#define BODY_ANIM_MINIGUN_SWIM_FIRELONG 31
//#define BODY_ANIM_MINIGUN_SWIM_FIRESHORT 32

//#define BODY_ANIM_DEATH_UNDERWATER 33
//#define BODY_ANIM_DEATH_UNDERWATERIDLE 34
//#define BODY_ANIM_DEATH_BACK 35
//#define BODY_ANIM_DEATH_EASYFALLBACK 36
//#define BODY_ANIM_DEATH_FORWARD 37
//#define BODY_ANIM_DEATH_EASYFALLFORWARD 38
//#define BODY_ANIM_DEATH_SPIKES 39

//#define BODY_ANIM_COLT_REDRAWSLOW 40
//#define BODY_ANIM_COLT_DEACTIVATETOWALK 41

//#define BODY_ANIM_SHOTGUN_REDRAWSLOW 42
//#define BODY_ANIM_SHOTGUN_DEACTIVATETOWALK 43
//#define BODY_ANIM_MINIGUN_REDRAWSLOW 44
//#define BODY_ANIM_MINIGUN_DEACTIVATETOWALK 45
//#define BODY_ANIM_STATUE_PULL 46
//#define BODY_ANIM_LOOKAROUNDONCE 47
//#define BODY_ANIM_WAIT 48
//#define BODY_ANIM_WAITTOLOOKAROUND 49
//#define BODY_ANIM_LOOKAROUNDTOWAIT 50
//#define BODY_ANIM_LOOKAROUND 51
//#define BODY_ANIM_NORMALWALK 52
//#define BODY_ANIM_SPAWNPOSE 53
//#define BODY_ANIM_BRIDGEFALLPOSE 54
//#define BODY_ANIM_KEYLIFT 55
//#define BODY_ANIM_ABYSSFALL 56
//#define BODY_ANIM_SPAWN_FALLDOWN 57
//#define BODY_ANIM_SPAWN_GETUP 58
//#define BODY_ANIM_ENTERSPACESHIP 59

// Color names

// Patch names

// Names of collision boxes
#define BODY_COLLISION_BOX_STAND 0

// Attaching position names
//#define BODY_ATTACHMENT_HEAD 0
#define BODY_ATTACHMENT_COLT_RIGHT 1
#define BODY_ATTACHMENT_KNIFE 2
#define BODY_ATTACHMENT_SINGLE_SHOTGUN 3
#define BODY_ATTACHMENT_DOUBLE_SHOTGUN 4
#define BODY_ATTACHMENT_FLAMER 5
#define BODY_ATTACHMENT_TOMMYGUN 6
#define BODY_ATTACHMENT_CANNON 7
#define BODY_ATTACHMENT_GRENADE_LAUNCHER 8
#define BODY_ATTACHMENT_LASER 9
#define BODY_ATTACHMENT_MINIGUN 10
#define BODY_ATTACHMENT_ROCKET_LAUNCHER 11
#define BODY_ATTACHMENT_COLT_LEFT 12
#define BODY_ATTACHMENT_ITEM 13
//#define BODY_ATTACHMENT_NOT LOADED 14
//#define BODY_ATTACHMENT_NOT LOADED 15
#define BODY_ATTACHMENT_HEAD 16

// Sound names
