// Animation names
#define SCORPMAN_ANIM_DEFAULT_ANIMATION 0
#define SCORPMAN_ANIM_WALK1 1
#define SCORPMAN_ANIM_TOFIRE 2
#define SCORPMAN_ANIM_FROMFIRE 3
#define SCORPMAN_ANIM_ATTACK2 4
#define SCORPMAN_ANIM_ATTACK3 5
#define SCORPMAN_ANIM_ATTACK4 6
#define SCORPMAN_ANIM_DEATH 7
#define SCORPMAN_ANIM_DEATHREST 8
#define SCORPMAN_ANIM_STAND 9
#define SCORPMAN_ANIM_WOUND1 10
#define SCORPMAN_ANIM_WOUND3 11
#define SCORPMAN_ANIM_WOUND2 12

// Color names

// Patch names

// Names of collision boxes
#define SCORPMAN_COLLISION_BOX_DEFAULT 0
#define SCORPMAN_COLLISION_BOX_DEATH 1

// Attaching position names
#define SCORPMAN_ATTACHMENT_MINIGUN 0

// Sound names
