// Animation names
#define KNIFE_ANIM_DEFAULT_ANIMATION 0
#define KNIFE_ANIM_PULL 1
#define KNIFE_ANIM_PULLOUT 2
#define KNIFE_ANIM_PULLOUT2 3
#define KNIFE_ANIM_PULLOUT3 4
#define KNIFE_ANIM_STAND1A 5
#define KNIFE_ANIM_STAND1ATTACK01 6
#define KNIFE_ANIM_STAND1ATTACK03 7
#define KNIFE_ANIM_STAND1B 8
#define KNIFE_ANIM_STAND1TOSTAND2 9
#define KNIFE_ANIM_STAND1TOSTAND3 10
#define KNIFE_ANIM_STAND2A 11
#define KNIFE_ANIM_STAND2ATTACK01 12
#define KNIFE_ANIM_STAND2ATTACK02 13
#define KNIFE_ANIM_STAND2ATTACK03 14
#define KNIFE_ANIM_STAND2B 15
#define KNIFE_ANIM_STAND2C 16
#define KNIFE_ANIM_STAND2TOSTAND1 17
#define KNIFE_ANIM_STAND2TOSTAND3 18
#define KNIFE_ANIM_STAND3A 19
#define KNIFE_ANIM_STAND3ATTACK01 20
#define KNIFE_ANIM_STAND3ATTACK02 21
#define KNIFE_ANIM_STAND3B 22
#define KNIFE_ANIM_STAND3TOSTAND2 23

// Color names

// Patch names

// Names of collision boxes
#define KNIFE_COLLISION_BOX_PART_NAME 0

// Attaching position names
#define KNIFE_ATTACHMENT_KNIFEITEM 0

// Sound names
